"""add current_streak column to user

Revision ID: 0b4fe47ae2d7
Revises: af5ecdb57c03
Create Date: 2025-04-11 19:51:28.613848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4fe47ae2d7'
down_revision: Union[str, None] = 'af5ecdb57c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_streak', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    ...
    # ### end Alembic commands ###
