"""Another table for pfp

Revision ID: 302db95c6cc7
Revises: d4bdbe5ab3f0
Create Date: 2025-04-11 17:32:57.166535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '302db95c6cc7'
down_revision: Union[str, None] = 'd4bdbe5ab3f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    ...


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    ...
    # ### end Alembic commands ###
