"""Add tags to jar models

Revision ID: 689b9034392d
Revises: b7b0309b3ba2
Create Date: 2025-04-09 21:54:31.270961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '689b9034392d'
down_revision: Union[str, None] = 'b7b0309b3ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('campaigns', 'tags')
    # ### end Alembic commands ###
