"""add pfp column to user

Revision ID: 912d9debc8cf
Revises: 302db95c6cc7
Create Date: 2025-04-11 17:45:18.373886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '912d9debc8cf'
down_revision: Union[str, None] = '302db95c6cc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.add_column('users', sa.Column('profile_picture', sa.LargeBinary(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    ...
    # ### end Alembic commands ###
