"""Add pfp column to user

Revision ID: d4bdbe5ab3f0
Revises: 689b9034392d
Create Date: 2025-04-09 23:09:56.608026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4bdbe5ab3f0'
down_revision: Union[str, None] = '689b9034392d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('profile_picture', sa.LargeBinary(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    ...
    # ### end Alembic commands ###
